#!/usr/bin/node

var fs = require('fs');
var child = require('child_process');

var doExit = function(err, info) {
  console.error(err, info === undefined ? '' : JSON.stringify(info));
  process.exit(1);
};

var getFullPath = function(path, name) {
  return path.charAt(path.length - 1) == '/' || name.charAt(0) == '/' ? path + name : path + '/' + name;
};

var serial = function(items, func, itemsDoneCallback) { // destroys items array (shift)
  if (items.length == 0) {
    itemsDoneCallback();
  } else {
    func(items.shift(), function() {
      serial(items, func, itemsDoneCallback);
    });
  }
};

var guessEncoding = function(buffer, len) {

  var nZeroOdd = 0;
  var nZeroEven = 0;
  var nControl = 0;
  var nASCII = 0;
  var nHigh = 0;
  var nOther = 0;;

  for (var i = 0; i < len; ++i) {
    var bi = buffer[i];
    if (bi == 0x00)
      i % 2  == 0 ? ++nZeroEven : ++nZeroOdd;
    else if (bi < 0x09)
      ++nOther;
    else if (bi <= 0x0d)
      ++nControl;
    else if (bi < 0x20)
      ++nOther;
    else if (bi < 0x80)
      ++nASCII;
    else
      ++nHigh;
  }

  if (len == nASCII + nControl)
    return {encoding: 'ascii', skip: 0};

  if (len > 2 && nZeroOdd  > (len - 2) / 3 && buffer[0] == 0xff && buffer[1] == 0xfe)
    return {encoding: 'utf16le', skip: 2};

  if (len > 3 && buffer[0] == 0xef && buffer[1] == 0xbb && buffer[2] == 0xbf)
    return {encoding: 'utf8', skip: 3};

  return {encoding: 'binary', skip: 0};
};

var grep = function(re, file, grepDoneCallback) {
  fs.open(file, 'r', function(err, fd) {
    if (err) {
      if (err.code != 'EACCES' || argTab.e.value == null)
        console.error('***', err.code, file);
      grepDoneCallback();
    } else {
      var chunk = new Buffer(25600);
      var encodingInfo = null;
      var str = '';
      var nLines = 0;
      var maxLineLength = 2048;
      var abort = false;

      var handleRead = function(err, bytesRead, chunk) {
        if (err) {
          if (err.code != 'EACCES' || argTab.e.value == null)
            console.error('***', err.code, file);
          grepDoneCallback();
        } else {
          if (encodingInfo == null)
            encodingInfo = guessEncoding(chunk, bytesRead);
          //if (encodingInfo.encoding != 'ascii' && encodingInfo.encoding != 'binary') console.log('\n@@@@ ' + encodingInfo.encoding + ' ' + file + '\n');
          if (encodingInfo.encoding != 'binary') {
            if (bytesRead > 0) {
              str += chunk.toString(encodingInfo.encoding, encodingInfo.skip, bytesRead);
              encodingInfo.skip = 0;
            }

            if (str.length > 0) {
              var e = bytesRead == 0 ? str.length : str.indexOf('\n');
              if (e < maxLineLength) {
                while (e != -1) {
                  line = str.substring(0, e > 0 && str.charAt(e - 1) == '\r' ? e - 1 : e);
                  ++nLines;
                  if (re.test(line))
                    process.stdout.write(file + ':' + nLines + ':' + line + '\n');
                  str = str.substring(e + 1);
                  e = str.indexOf('\n');
                }
              } else {
                if (!argTab.e.value)
                  process.stdout.write(file + ':' + nLines + ': LINE TOO LONG (' + maxLineLength + ')\n');
                abort = true;
              }
            }

          }
          if (!abort && bytesRead > 0 && encodingInfo.encoding != 'binary') {
            fs.read(fd, chunk, 0, chunk.length, null, handleRead);
          } else {
            fs.close(fd);
            grepDoneCallback();
          }
        }
      };

      fs.read(fd, chunk, 0, 256, null, handleRead);  // only 256 for encoding check
    }
  });
};

var cksum = function(file, cksumDoneCallback) {
  fs.open(file, 'r', function(err, fd) {
    if (err) {
      if (err.code != 'EACCES' || argTab.e.value == null)
        console.error('***', err.code, file);
      cksumDoneCallback();
    } else {
      var chunk = new Buffer(25000);
      var encodingInfo = null;
      var crc = 0;
      var nBytes = 0;

      var handleRead = function(err, bytesRead, chunk) {
        if (err) {
          if (err.code != 'EACCES' || argTab.e.value == null)
            console.error('***', err.code, file);
          cksumDoneCallback();
        } else {
          if (bytesRead > 0) {
            nBytes += bytesRead;
            totalSum += nBytes;
            for (var i = 0; i < bytesRead; ++i)
              crc = crctab[chunk[i] ^ ((crc >>> 24) & 0xFF)] ^ (crc << 8);
            fs.read(fd, chunk, 0, chunk.length, null, handleRead);
          } else {
            var n = nBytes;
            while (n > 0) {
              crc = crctab[(n & 0xFF) ^ ((crc >> 24) & 0xFF)] ^ (crc << 8);
              n >>= 8;
            }
            crc = crc ^ -1;
            totalCksum += crc;

            fs.close(fd);
            process.stdout.write((crc >>> 0) + ' ' + nBytes + ' ' + file + '\n'); // shift trick to make 32 bit unsigned
            cksumDoneCallback();
          }
        }
      };

      fs.read(fd, chunk, 0, chunk.length, null, handleRead);
    }
  });
};

var userMap = [];
var groupMap = [];
var needUserMaps;
var parms = [];

var parseArgs = function(args) {
  var now = new Date();
  for (var i = 0; i < args.length; ++i) {
    var arg = args[i];
    if (arg.charAt(0) == '-') {
      var argTabEntry = argTab[arg.substring(1)];
      if (argTabEntry === undefined || (i + 1 >= args.length && argTabEntry.type != 'b'))
        doExit('Invalid Option', arg);
      if (argTabEntry.value != null)
        doExit('Option can only appear once', arg);
      switch (argTabEntry.type) {
        case 'b':
          argTabEntry.value =  true;
          break;
        case 's':
          argTabEntry.value =  args[++i];
          break;
        case 'r':
          argTabEntry.value =  new RegExp('^' + args[++i] + '$', argTab.i.value !== null ? 'i' : '');
          break;
        case 'x':
          argTabEntry.value =  new RegExp(args[++i], argTab.i.value !== null ? 'i' : '');
          break;
        case 'e':
          var list = args[++i].split(',').join('|');
          argTabEntry.value =  new RegExp('\\.(' + list + ')$', argTab.i.value !== null ? 'i' : '');
          break;
        case 't': // time
          var matches = args[++i].match(/^([0-9]+)([smhd]?)$/);
          if (matches === null) doExit('Invalid time specifier: ' + args[i]);
          var time = parseInt(matches[1], 10);
          switch (matches[2]) {
            case 'm': time *= 60;           break;
            case 'h': time *= 60 * 60;      break;
            case 'd': time *= 60 * 60 * 24; break;
          }
          argTabEntry.value = now.getTime() - time * 1000;
          break;
        case 'z': // size
          var matches = args[++i].match(/^([0-9]+)([bkmg]?)$/);
          if (matches === null) doExit('Invalid time specifier: ' + args[i]);
          var size = parseInt(matches[1], 10);
          switch (matches[2]) {
            case 'k': size *= 1000;       break;
            case 'm': size *= 1000000;    break;
            case 'g': size *= 1000000000; break;
          }
          argTabEntry.value = size;
          break;
        case 'i': // int
          var matches = args[++i].match(/^([0-9]+)$/);
          if (matches === null) doExit('Invalid int specifier: ' + args[i]);
          var int = parseInt(matches[1], 10);
          argTabEntry.value = int;
          break;
      }
    } else {
      parms.push(arg);
    }
  };
};

var getUserMaps = function(userMapsDoneCallback) {
  if (needUserMaps) {
    var done = 0;
    child.exec('getent passwd', function (error, stdout, stderr) {
      if (error)
        doExit(error, 'getent passwd');
      stdout.split('\n').forEach(function(line) {
        var cols = line.split(':');
        userMap[cols[2]] = cols[0];
      });
      if (++done == 2)
        userMapsDoneCallback();
    });
    child.exec('getent group', function (error, stdout, stderr) {
      if (error)
        doExit(error, 'getent group');
      stdout.split('\n').forEach(function(line) {
        var cols = line.split(':');
        groupMap[cols[2]] = cols[0];
      });
      if (++done == 2)
        userMapsDoneCallback();
    });
  } else
    userMapsDoneCallback();
};

var processEntry = function(xdev, path, name, depth, handler, entryDoneCallback) {
  var fullPath = getFullPath(path, name);
  fs.lstat(fullPath, function(err, stats) {
    handler(err, xdev, path, name, stats, function() {
      if (!err && xdev == stats.dev && stats.isDirectory() && --depth >= 0) {
        fs.readdir(fullPath, function(err, files) {
          if (err) {
            handler(err, xdev, path, name, null, function() {
              entryDoneCallback();
            });
          } else {
            serial(files, function(file, fileDoneCallback) {
              processEntry(xdev, fullPath, file, depth, handler, fileDoneCallback);
            }, entryDoneCallback);
          }
        });
      } else
        entryDoneCallback();
    });
  });
};

var processDir = function(path, depth, handler, dirDoneCallback) {
  fs.lstat(path, function(err, stats) {
    if (err)
      doExit(err, {path: path});
    if (!stats.isDirectory())
      doExit('Must be a directory', {path: path});
    var xdev = stats.dev;
    fs.readdir(path, function(err, files) {
      if (err) {
        doExit(err, {path: path});
      } else {
        serial(files, function(file, fileDoneCallback) {
          processEntry(xdev, path, file, depth, handler, fileDoneCallback);
        }, dirDoneCallback);
      }
    });
  });
};

var typeString = function(stats) {
  if (stats.isFile()) return 'f';
  if (stats.isDirectory()) return 'd';
  if (stats.isSymbolicLink()) return 'l';
  if (stats.isBlockDevice()) return 'b';
  if (stats.isCharacterDevice()) return 'c';
  if (stats.isFIFO()) return 'p';
  if (stats.isSocket()) return 's';
  return '?';
};

var permString = function(stats) {
  var mode = stats.mode;
  return (((mode & 0400) != 0) ? 'r' : '-')
    + (((mode & 0200) != 0) ? 'w' : '-')
    + (((mode & 0100) != 0) ? 'x' : '-')
    + (((mode & 040)  != 0) ? 'r' : '-')
    + (((mode & 020)  != 0) ? 'w' : '-')
    + (((mode & 010)  != 0) ? 'x' : '-')
    + (((mode & 04)   != 0) ? 'r' : '-')
    + (((mode & 02)   != 0) ? 'w' : '-')
    + (((mode & 01)   != 0) ? 'x' : '-');
};

var permOctalString = function(stats) {
  return padZero((stats.mode & 0777).toString(8), 3);
};

var modeLSString = function(stats) {
  var mode = stats.mode;
  var ox = mode & 04100;  // suid
  var gx = mode & 02010;  // guid
  var wx = mode & 01001;  // sticky
  return (stats.isFile() ? '-' : typeString(stats))
    + (((mode & 0400) != 0) ? 'r' : '-')
    + (((mode & 0200) != 0) ? 'w' : '-')
    + (ox == 00000 ? '-' : ox == 00100 ? 'x' : ox == 04100 ? 's' : 'S')
    + (((mode & 040)  != 0) ? 'r' : '-')
    + (((mode & 020)  != 0) ? 'w' : '-')
    + (gx == 00000 ? '-' : gx == 00010 ? 'x' : gx == 02010 ? 's' : 'S')
    + (((mode & 04)   != 0) ? 'r' : '-')
    + (((mode & 02)   != 0) ? 'w' : '-')
    + (wx == 00000 ? '-' : wx == 00001 ? 'x' : wx == 01001 ? 't' : 'T');
};

var pad = function(s, n) {
  return s.length >= n ? s : ('                                                             ' + s).slice(-n);
};

var padZero = function(s, n) {
  return s.length >= n ? s : ('0000000000000000000000000000000000000000000000000000000000000' + s).slice(-n);
};

var two = function(n) {
  return n < 10 ? '0' + n : '' + n;
};

var dateToString = function(date) {
  return date.getFullYear() + '-' + two(date.getMonth() + 1) + '-' + two(date.getDate())
    + ' ' + two(date.getHours()) + ':' + two(date.getMinutes()) + ':' + two(date.getSeconds());
};

var argTab = {
  'name':    {type: 'x', value: null},
  '^name':   {type: 'x', value: null},
  'fname':   {type: 'x', value: null},
  '^fname':  {type: 'x', value: null},
  'ext':     {type: 'e', value: null},
  '^ext':    {type: 'e', value: null},
  'type':    {type: 'x', value: null},
  '^type' :  {type: 'x', value: null},
  'mtime':   {type: 't', value: null},
  '^mtime':  {type: 't', value: null},
  'atime':   {type: 't', value: null},
  '^atime':  {type: 't', value: null},
  'ctime':   {type: 't', value: null},
  '^ctime':  {type: 't', value: null},
  'btime':   {type: 't', value: null},
  '^btime':  {type: 't', value: null},
  'size':    {type: 'z', value: null},
  '^size':   {type: 'z', value: null},
  'user':    {type: 'x', value: null},
  '^user':   {type: 'x', value: null},
  'group':   {type: 'x', value: null},
  '^group':  {type: 'x', value: null},
  'perm':    {type: 'x', value: null},
  '^perm':   {type: 'x', value: null},
  'suid':    {type: 'b', value: null},
  '^suid':   {type: 'b', value: null},
  'guid':    {type: 'b', value: null},
  '^guid':   {type: 'b', value: null},
  'sticky':  {type: 'b', value: null},
  '^sticky': {type: 'b', value: null},

  'print':   {type: 'b', value: null},
  'print0':  {type: 'b', value: null},
  'ls':      {type: 'b', value: null},
  'stat':    {type: 'b', value: null},
  'grep':    {type: 'x', value: null},
  'cksum':   {type: 'b', value: null},
  'sum':     {type: 'b', value: null},

  'i':       {type: 'b', value: null},
  'e':       {type: 'b', value: null},
  'depth':   {type: 'i', value: null},
};

var totalSum = 0;
var totalCksum = 0;

var handleOne = function(err, xdev, path, name, stats, handlerCallback) {
  var fullPath = getFullPath(path, name);
  var isAsync = false;
  if (err) {
    if (err.code != 'EACCES' || argTab.e.value == null)
      console.error('***', err.code, fullPath);
  } else {
    var doAction = true;

    if (doAction && argTab.name.value !== null && !argTab.name.value.test(name))
      doAction = false;
    if (doAction && argTab['^name'].value != null && argTab['^name'].value.test(name))
      doAction = false;

    if (doAction && argTab.fname.value !== null && !argTab.fname.value.test(fullPath))
      doAction = false;
    if (doAction && argTab['^fname'].value != null && argTab['^fname'].value.test(fullPath))
      doAction = false;

    if (doAction && argTab.ext.value !== null && !argTab.ext.value.test(name))
      doAction = false;
    if (doAction && argTab['^ext'].value != null && argTab['^ext'].value.test(name))
      doAction = false;

    if (doAction && argTab.type.value !== null && !argTab.type.value.test(typeString(stats)))
      doAction = false;
    if (doAction && argTab['^type'].value != null && argTab['^type'].value.test(typeString(stats)))
      doAction = false;

    if (doAction && argTab.mtime.value !== null && argTab.mtime.value > stats.mtime.getTime()) // no show if file modified before arg time
      doAction = false;
    if (doAction && argTab['^mtime'].value != null && !(argTab['^mtime'].value > stats.mtime.getTime()))
      doAction = false;

    if (doAction && argTab.size.value !== null && argTab.size.value < stats.size) // no show if file modified before arg time
      doAction = false;
    if (doAction && argTab['^size'].value != null && argTab['^size'].value >= stats.size)
      doAction = false;

    if (doAction && argTab.atime.value !== null && argTab.atime.value > stats.atime.getTime()) // no show if file accessed before arg time
      doAction = false;
    if (doAction && argTab['^atime'].value != null && !(argTab['^atime'].value > stats.atime.getTime()))
      doAction = false;

    if (doAction && argTab.ctime.value !== null && argTab.ctime.value > stats.ctime.getTime()) // no show if file changed before arg time
      doAction = false;
    if (doAction && argTab['^ctime'].value != null && !(argTab['^ctime'].value > stats.ctime.getTime()))
      doAction = false;

    if (doAction && argTab.btime.value !== null && argTab.btime.value > stats.birthtime.getTime()) // no show if file birthed before arg time
      doAction = false;
    if (doAction && argTab['^btime'].value != null && !(argTab['^btime'].value > stats.birthtime.getTime()))
      doAction = false;

    if (doAction && argTab.user.value !== null && !(argTab.user.value.test(stats.uid) || argTab.user.value.test(userMap[stats.uid])))
      doAction = false;
    if (doAction && argTab['^user'].value != null && (argTab['^user'].value.test(stats.uid) || argTab['^user'].value.test(userMap[stats.uid])))
      doAction = false;

    if (doAction && argTab.group.value !== null && !(argTab.group.value.test(stats.gid) || argTab.group.value.test(groupMap[stats.gid])))
      doAction = false;
    if (doAction && argTab['^group'].value != null && (argTab['^group'].value.test(stats.gid) || argTab['^group'].value.test(groupMap[stats.gid])))
      doAction = false;

    if (doAction && argTab.perm.value !== null && !(argTab.perm.value.test(permString(stats)) || argTab.perm.value.test(permOctalString(stats))))
      doAction = false;
    if (doAction && argTab['^perm'].value != null && (argTab['^perm'].value.test(permString(stats)) || argTab['^perm'].value.test(permOctalString(stats))))
      doAction = false;

    if (doAction && argTab.suid.value !== null && !((stats.mode & 04000) == 04000))
      doAction = false;
    if (doAction && argTab['^suid'].value != null && (stats.mode & 04000) == 04000)
      doAction = false;

    if (doAction && argTab.guid.value !== null && !((stats.mode & 02000) == 02000))
      doAction = false;
    if (doAction && argTab['^guid'].value != null && (stats.mode & 02000) == 02000)
      doAction = false;

    if (doAction && argTab.sticky.value !== null && !((stats.mode & 01000) == 01000))
      doAction = false;
    if (doAction && argTab['^sticky'].value != null && (stats.mode & 01000) == 01000)
      doAction = false;

    if (doAction) {
      if (argTab.stat.value)
        process.stdout.write(fullPath + ' ' + JSON.stringify(stats, null, 0) + '\n');
      if (argTab.ls.value)
        process.stdout.write(modeLSString(stats) + ' ' +  pad(userMap[stats.uid] || stats.uid, 8) + ' ' +  pad(groupMap[stats.gid] || stats.gid, 8) + ' ' +
                             pad(stats.size, 13) + ' ' +  dateToString(stats.mtime) + ' ' +  fullPath + '\n');
      if (argTab.print.value)
        process.stdout.write(fullPath + '\n');
      if (argTab.print0.value)
        process.stdout.write(fullPath + '\0');

      if (argTab.sum.value && stats.isFile())
        totalSum += stats.size;

      if (argTab.grep.value != null) {
        grep(argTab.grep.value, fullPath, handlerCallback);
        isAsync = true;
      }

      if (argTab.cksum.value != null) {
        cksum(fullPath, handlerCallback);
        isAsync = true;
      }

    }
  }
  if (!isAsync)
    handlerCallback();
};

var usage = function() {
  return 'usage: ff [options] dir1...\n' +
    'Find files satisfying a set of files and perform an action - like find with simplified syntax\n' +
    '\n' +
    ' Filters:\n' +
    '  -name regex,  -^name regex    file name matches regex \n' +
    '  -fname regex, -^fname regex   full path matches regex    \n' +
    '  -ext csv,     -^ext csv       extension matches one of csv extensions w/o "."    \n' +
    '  -type regex,  -^type regex    entry type matches regex (types are 1 char in [fdlbcps])    \n' +
    '  -mtime time,  -^mtime time    modify time <= time    \n' +
    '  -atime time,  -^atime time    access time <= time  \n' +
    '  -ctime time,  -^ctime time    change / create time <= time  \n' +
    '  -btime time,  -^btime time    birth time <= time (see node fs.Stats) \n' +
    '  -size size,   -^size size     file size <= size   \n' +
    '  -user regex,  -^user regex    file owner user / user ID matches regex  \n' +
    '  -group regex, -^group regex   file owner group / group ID matches regex   \n' +
    '  -perm regex,  -^perm regex    file permissions string / octal string matches regex  \n' +
    '  -suid,        -^suid          file has suid bit set\n' +
    '  -guid,        -^guid          file has guid bit set\n' +
    '  -sticky,      -^sticky        file has sticky bit set\n' +
    ' Modifiers:\n' +
    '  -i                            any regex\'s that follow are case insensitive  \n' +
    '  -e                            any access or line too long (grep) errors are silently ignored    \n' +
    '  -depth                        max directory descend depth, 0 is top only, default is all depths    \n' +
    ' Actions:\n' +
    '  -print                        print full path (default action) \n' +
    '  -print0                       print full path with \\0 separator for xargs\n' +
    '  -ls                           print ls type listing\n' +
    '  -stat                         print raw stat result in JSON format \n' +
    '  -grep regex                   print lines in file matching regex   \n' +
    '  -sum                          print final sum of size of all file entries \n' +
    '  -cksum                        print cksum of file \n' +
    '\n' +
    ' - regex "matches" means "contains" - use regex ^ and $ for beginning and end of string \n' +
    ' - watch out for shell wildcards / globbing - safest to put regex in quotes \n' +
    ' - regex chars used literally, e.g. "." need to be escaped ("any" char vs "period") \n' +
    ' - time is a numeric value in seconds, numeric value can have a final m, h, d for minutes, hours, or days \n' +
    ' - size is a numeric value in bytes, numeric value can have a final k, m, g for thousand, mega, or giga bytes \n' +
    ' - permission is string like rwxrwxr-x or 775; a regex matching either will activate the filter \n' +
    ' - user and group regex can match the string or numeric value to activate the filter \n' +
    ' - all options, modifiers, actions, and dirs can be specified in any order; filters all must be satisfied to fire action \n' +
    ' - find style "xdev" is default, i.e. don\'t descend dirs on other file systems \n' +
    ' - linux getent command is spawned to get user and group names from system when needed \n' +
    '\n' +
    ' Examples:\n' +
    '  ff ~ -mtime 3m -type f -name \'\\.(js|cc|dart)$\' -ls    # modified last 3 minutes, "file", extension is .js, .cc, or .dart \n' +
    '  ff / -^user \'(dave|0)\' -ls -e                         # find files or dirs with owners other than dave or root (0), skip access errors \n' +
    '  ff . -fname \'/obj$\' -type d -print0 | xargs -0 rm -rf # rm dirs containing path element "obj" \n' +
    '  ff ~ -^size 10m -ls                                   # files with size > 10 000 000 bytes \n' +
    '  ff ~ -size 0 -ls                                      # files with size == 0 bytes \n' +
    '  ff ~ -type l -ls                                      # show links \n' +
    '  ff ~ -type f -i -grep sqlite_busy                     # show lines in files containing case-insensitive SQLITE_BUSY \n' +
    '  ff . -ext cc,c,java                                   # files with extension\n' +
    '';
};

var main = function() {
  try {
    parseArgs(process.argv.slice(2));
  } catch (e) {
    doExit(e.message);
  }
  if (parms.length == 0)
    doExit(usage());
  if (!argTab.print.value && !argTab.ls.value && !argTab.stat.value && !argTab.print0.value && !argTab.grep.value && !argTab.sum.value && !argTab.cksum.value)
    argTab.print.value = true;
  needUserMaps = argTab.ls.value || argTab.user.value || argTab['^user'].value || argTab.group.value || argTab['^group'].value;

  var nChecked = 0;
  for (var i = 0; i < parms.length; ++i) {
    var pi = parms[i];
    fs.lstat(pi, function(err, stats) {
      if (err || !stats.isDirectory())
        doExit(err || 'Parameter must be a directory', pi);
      if (++nChecked == parms.length) {
        getUserMaps(function() {
          serial(parms, function(parm, dirDoneCallback) {
            processDir(parm, argTab.depth.value !== null ? argTab.depth.value : 999999999, handleOne, dirDoneCallback);
          }, function() {
            if (argTab.sum.value)
              process.stdout.write('sum: ' + totalSum.toLocaleString() + '\n');
            if (argTab.cksum.value)
              process.stdout.write('cksum: ' + (totalCksum >>> 0) + ' ' + totalSum + '\n'); // unsigned trick
            process.exitCode = 0;
          });
        });
      }
    });
  }
};

main();

// /opt/dart-sdk/lib/typed_data/typed_data.dart {"dev":2051,"mode":33188,"nlink":1,"uid":0,"gid":0,"rdev":0,
//"blksize":4096,"ino":131274,"size":61686,"blocks":128,"atime":"2015-03-13T23:54:06.000Z","mtime":"2014-11-27T08:55:03.000Z",
//"ctime":"2015-03-13T23:54:06.000Z","birthtime":"2015-03-13T23:54:06.000Z"}

var crctab = [
  0x00000000,
  0x04c11db7, 0x09823b6e, 0x0d4326d9, 0x130476dc, 0x17c56b6b,
  0x1a864db2, 0x1e475005, 0x2608edb8, 0x22c9f00f, 0x2f8ad6d6,
  0x2b4bcb61, 0x350c9b64, 0x31cd86d3, 0x3c8ea00a, 0x384fbdbd,
  0x4c11db70, 0x48d0c6c7, 0x4593e01e, 0x4152fda9, 0x5f15adac,
  0x5bd4b01b, 0x569796c2, 0x52568b75, 0x6a1936c8, 0x6ed82b7f,
  0x639b0da6, 0x675a1011, 0x791d4014, 0x7ddc5da3, 0x709f7b7a,
  0x745e66cd, 0x9823b6e0, 0x9ce2ab57, 0x91a18d8e, 0x95609039,
  0x8b27c03c, 0x8fe6dd8b, 0x82a5fb52, 0x8664e6e5, 0xbe2b5b58,
  0xbaea46ef, 0xb7a96036, 0xb3687d81, 0xad2f2d84, 0xa9ee3033,
  0xa4ad16ea, 0xa06c0b5d, 0xd4326d90, 0xd0f37027, 0xddb056fe,
  0xd9714b49, 0xc7361b4c, 0xc3f706fb, 0xceb42022, 0xca753d95,
  0xf23a8028, 0xf6fb9d9f, 0xfbb8bb46, 0xff79a6f1, 0xe13ef6f4,
  0xe5ffeb43, 0xe8bccd9a, 0xec7dd02d, 0x34867077, 0x30476dc0,
  0x3d044b19, 0x39c556ae, 0x278206ab, 0x23431b1c, 0x2e003dc5,
  0x2ac12072, 0x128e9dcf, 0x164f8078, 0x1b0ca6a1, 0x1fcdbb16,
  0x018aeb13, 0x054bf6a4, 0x0808d07d, 0x0cc9cdca, 0x7897ab07,
  0x7c56b6b0, 0x71159069, 0x75d48dde, 0x6b93dddb, 0x6f52c06c,
  0x6211e6b5, 0x66d0fb02, 0x5e9f46bf, 0x5a5e5b08, 0x571d7dd1,
  0x53dc6066, 0x4d9b3063, 0x495a2dd4, 0x44190b0d, 0x40d816ba,
  0xaca5c697, 0xa864db20, 0xa527fdf9, 0xa1e6e04e, 0xbfa1b04b,
  0xbb60adfc, 0xb6238b25, 0xb2e29692, 0x8aad2b2f, 0x8e6c3698,
  0x832f1041, 0x87ee0df6, 0x99a95df3, 0x9d684044, 0x902b669d,
  0x94ea7b2a, 0xe0b41de7, 0xe4750050, 0xe9362689, 0xedf73b3e,
  0xf3b06b3b, 0xf771768c, 0xfa325055, 0xfef34de2, 0xc6bcf05f,
  0xc27dede8, 0xcf3ecb31, 0xcbffd686, 0xd5b88683, 0xd1799b34,
  0xdc3abded, 0xd8fba05a, 0x690ce0ee, 0x6dcdfd59, 0x608edb80,
  0x644fc637, 0x7a089632, 0x7ec98b85, 0x738aad5c, 0x774bb0eb,
  0x4f040d56, 0x4bc510e1, 0x46863638, 0x42472b8f, 0x5c007b8a,
  0x58c1663d, 0x558240e4, 0x51435d53, 0x251d3b9e, 0x21dc2629,
  0x2c9f00f0, 0x285e1d47, 0x36194d42, 0x32d850f5, 0x3f9b762c,
  0x3b5a6b9b, 0x0315d626, 0x07d4cb91, 0x0a97ed48, 0x0e56f0ff,
  0x1011a0fa, 0x14d0bd4d, 0x19939b94, 0x1d528623, 0xf12f560e,
  0xf5ee4bb9, 0xf8ad6d60, 0xfc6c70d7, 0xe22b20d2, 0xe6ea3d65,
  0xeba91bbc, 0xef68060b, 0xd727bbb6, 0xd3e6a601, 0xdea580d8,
  0xda649d6f, 0xc423cd6a, 0xc0e2d0dd, 0xcda1f604, 0xc960ebb3,
  0xbd3e8d7e, 0xb9ff90c9, 0xb4bcb610, 0xb07daba7, 0xae3afba2,
  0xaafbe615, 0xa7b8c0cc, 0xa379dd7b, 0x9b3660c6, 0x9ff77d71,
  0x92b45ba8, 0x9675461f, 0x8832161a, 0x8cf30bad, 0x81b02d74,
  0x857130c3, 0x5d8a9099, 0x594b8d2e, 0x5408abf7, 0x50c9b640,
  0x4e8ee645, 0x4a4ffbf2, 0x470cdd2b, 0x43cdc09c, 0x7b827d21,
  0x7f436096, 0x7200464f, 0x76c15bf8, 0x68860bfd, 0x6c47164a,
  0x61043093, 0x65c52d24, 0x119b4be9, 0x155a565e, 0x18197087,
  0x1cd86d30, 0x029f3d35, 0x065e2082, 0x0b1d065b, 0x0fdc1bec,
  0x3793a651, 0x3352bbe6, 0x3e119d3f, 0x3ad08088, 0x2497d08d,
  0x2056cd3a, 0x2d15ebe3, 0x29d4f654, 0xc5a92679, 0xc1683bce,
  0xcc2b1d17, 0xc8ea00a0, 0xd6ad50a5, 0xd26c4d12, 0xdf2f6bcb,
  0xdbee767c, 0xe3a1cbc1, 0xe760d676, 0xea23f0af, 0xeee2ed18,
  0xf0a5bd1d, 0xf464a0aa, 0xf9278673, 0xfde69bc4, 0x89b8fd09,
  0x8d79e0be, 0x803ac667, 0x84fbdbd0, 0x9abc8bd5, 0x9e7d9662,
  0x933eb0bb, 0x97ffad0c, 0xafb010b1, 0xab710d06, 0xa6322bdf,
  0xa2f33668, 0xbcb4666d, 0xb8757bda, 0xb5365d03, 0xb1f740b4
];
